config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  root "main#index"
  
  get "/offers/:app_offer_id" => "main#offer"
  post "/offers/:app_offer_id" => "referrers#create"
  get "/refer" => "main#refer"
  get "/refer/:app_offer_id" => "main#refer"
  get "/referral" => "main#referral"
  get "/profile" => "main#profile"
  get "/postback" => "main#postback"
  post "/profile" => "app_redeems#create"
  get "/logout" => "main#logout"
  get 'google_login' => "logins#google_login"
  get "/gameaward/:award_id" => "gameaward#index"
  post "/gameaward/:award_id" => "gameaward#create"
  get '/admin' => 'admin/manager#new'
  post '/admin' => 'admin/manager#create'
  get '/admin/logout' => 'admin/manager#destroy'
 
 namespace :admin do 

  resources :campaign_infos
  resources :app_offers
  resources :referrers
  resources :affiliates     
  resources :articles
  resources :app_banners
  resources :game_awards
  resources :list_redeems
   
 end

  get "/admin/app_offers/:app_offer_id/edit/event/new" => "admin/event#new"
  post "/admin/app_offers/:app_offer_id/edit/event/new" => "admin/event#create"
  get "/admin/app_offers/:app_offer_id/edit/event/:event_id/edit" => "admin/event#edit"
  post "/admin/app_offers/:app_offer_id/edit/event/:event_id/edit" => "admin/event#update"
  get "/admin/app_offers/:app_offer_id/edit/event/:event_id/" => "admin/event#destroy"

  get "/admin/game_rewards/" => "admin/game_rewards#index"
  get "/admin/app_redeems/" => "admin/list_redeems#index"
  get "/admin/app_redeems/:id/" => "admin/list_redeems#show"
  get "/admin/app_redeems/:id/edit" => "admin/list_redeems#edit"
  post "/admin/app_redeems/:id/edit" => "admin/list_redeems#update"
  get "/admin/ref_user/:id" => "admin/ref_user#show"
  get "/admin/postbacks" => "admin/event_postbacks#index"

  post "/payout" => "list_redeems#payout"

end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
	paginates_per 10
	
end

app/models/app_banner.rb
class AppBanner < ApplicationRecord
	paginates_per 10
	
end

app/models/app_offer.rb
class AppOffer < ApplicationRecord
  paginates_per 10
  
  has_many :events
end

app/models/app_redeem.rb
class AppRedeem < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	paginates_per 10
	
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  paginates_per 10
  
  belongs_to :campaign_info , foreign_key: "campaign_info_id", class_name: "CampaignInfo"
end

app/models/campaign_info.rb
class CampaignInfo < ApplicationRecord
  paginates_per 10
  
  has_many :campaign
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :app_offer,foreign_key: "app_offer_id",class_name: "AppOffer"
end

app/models/event_postback.rb
class EventPostback < ApplicationRecord
	paginates_per 10
	
end

app/models/game_award.rb
class GameAward < ApplicationRecord
	paginates_per 10
	
end

app/models/game_reward.rb
class GameReward < ApplicationRecord
	paginates_per 10
	
end

app/models/list_redeem.rb
class ListRedeem < ApplicationRecord
	paginates_per 10
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_secure_password

  validates :username, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/postback.rb
class Postback < ApplicationRecord
	belongs_to :referrer
end

app/models/ref_user.rb
class RefUser < ApplicationRecord
end

app/models/referrer.rb
class Referrer < ApplicationRecord
	paginates_per 10
end

app/controllers/admin/referrers_controller.rb
module Admin
  class ReferrersController < ApplicationController

  layout  "admin"
  before_action :set_referrer, only: %i[ show edit update]

  def index
    if params[:paytm_number].present?
    @referrers = Referrer.where("paytm_number LIKE ?", "%#{params[:paytm_number]}%").order("id DESC").page(params[:page])
    @app_offers = AppOffer
    else
    @referrers = Referrer.all.order("created_at DESC").order("id DESC").page(params[:page])
    @app_offers = AppOffer
    end
  end

  def show
  end

  def new
    @referrer = Referrer.new
  end

  def edit
  end

  def create
    click_id = SecureRandom.hex(18)
    @app_offer_id = params["referrer"][:app_offer_id]
    app_offer = AppOffer.find_by(id: @app_offer_id)
    @referrer = Referrer.new(paytm_number:params["referrer"][:paytm_number],upi_id:params["referrer"][:upi_id],app_offer_id:params["referrer"][:app_offer_id],click_id:click_id,affiliate_id:params["referrer"][:affiliate_id])
    @refer_code = session[:referral_code]
      if @referrer.save
        puts params
          redirect_to "#{app_offer.action_url}?click_id=#{click_id}", allow_other_host: true
      else
        render :new, status: :unprocessable_entity
    end
  end

  def update
      if @referrer.update(referrer_params)
       redirect_to referrer_url(@referrer), notice: "Referrer was successfully updated."
      else
     render :edit, status: :unprocessable_entity
      end
  end

  private
    def set_referrer
      @referrer = Referrer.find(params[:id])
    end

    def referrer_params
      params.require(:referrer).permit(:paytm_number,:upi_id,:app_offer_id,:aff_status,:ref_status,:affiliate_id)
    end
end

end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/helpers/app_banners_helper.rb
module AppBannersHelper
end

app/helpers/app_offers_helper.rb
module AppOffersHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/referrers_helper.rb
module ReferrersHelper
end

app/views/admin/referrers/_form.html.erb
<%= form_with(model: referrer,url:admin_referrer_path class: "form-horizontal") do |form| %>
  <% if referrer.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(referrer.errors.count, "error") %> prohibited this app_offer from being saved:</h2>
      <ul>
        <% referrer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group p-2">
        <%= form.label :affiliate_id, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :affiliate_id, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :paytm_number, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :paytm_number, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :source_ip, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :source_ip, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :click_id, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :click_id, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :live_offer_id, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :live_offer_id, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :app_offer_id, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :app_offer_id, class: "form-control" %>
      </div>
      <div class="d-lg-flex gap-3 mt-4 me-5">
        <div class="form-group p-5 d-flex align-items-center gap-2 ">
          <%= form.label :aff_status, class: "control-label fs-5 fw-medium" %>
          <%= form.check_box :aff_status, class: "form-check-input" %>
        </div>
        <div class="form-group p-5 d-flex align-items-center gap-2">
          <%= form.label :ref_status, class: "control-label fs-5 fw-medium" %>
          <%= form.check_box :ref_status, class: "form-check-input" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group p-2">
        <%= form.label :aff_order_id, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :aff_order_id, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :aff_pay_response, class: "control-label fs-5 fw-medium" %>
        <%= form.text_area :aff_pay_response, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :ref_pay_response, class: "control-label fs-5 fw-medium" %>
        <%= form.text_area :ref_pay_response, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :upi_id, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :upi_id, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :telegram_id, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :telegram_id, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group p-2">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit "Save", class: "btn edit-save-btn text-light fw-medium" %>
    </div>
  </div>
<% end %>

app/views/admin/referrers/_referrer.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th scope="col" class="fs-5">Id</th>
    <th scope="col" class="fs-5">Paytm No.</th>
    <th scope="col" class="fs-5">Upi Id</th>
    <th scope="col" class="fs-5">Affiliate Id</th>
    <th scope="col" class="fs-5">Click Id</th>
    <th scope="col" class="fs-5">Offer</th>
    <th scope="col" class="fs-5">Status</th>
    <th scope="col" class="fs-5">Created At</th>
    <th scope="col" class="fs-5">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @referrers.each do |referrer| %>
    <tr>
      <th class="fs-6">
        <a href="/admin/referrers/<%= referrer.id %>"><%= referrer.id %></a>
      </th>
      <td class="fs-6">
        <%= referrer.paytm_number %>
      </td>
      <td class="fs-6">
        <%= referrer.upi_id %>
      </td>
      <th class="fs-6">
         <a href="/admin/affiliates/<%= referrer.affiliate_id %>"><%= referrer.affiliate_id %></a>
      </th>
      <td class="fs-6">
        <%= referrer.click_id %>
      <td class="fs-6">
        <% if referrer.app_offer_id %>
          <% app_offer = @app_offers.find_by(id: referrer.app_offer_id) %>
          <% if app_offer %>
            <a href="/admin/app_offers/<%= app_offer.id %>">
              <%= app_offer.offer_name %>
            </a>
          <% else %>
            Offer Not Found
          <% end %>
        <% else %>
          No App Offer ID
        <% end %>
      </td>
      <td class="fs-6">
        <% if referrer.ref_status %>
          <i class="fa-solid fa-check text-success fs-3" ></i>
        <% else %>
          <i class="fa-solid fa-xmark text-danger fs-3" ></i>
        <% end %>
      </td>
     <td class="fs-6">
       <%= referrer.created_at.strftime('%d/%m/%Y') %>
       &nbsp;
       <%= referrer.created_at.strftime('%I:%M:%S %p') %>
     </td>
      <td class="fs-5">
        <%= link_to "Edit",edit_admin_referrer_path(referrer),class:"btn btn-dark" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/referrers/edit.html.erb
  <div class="main-content container">
    <% if notice %>
      <div class="alert alert-warning" role="alert"><%= notice %></div>
    <% end %>
    <div class="ms-2 mt-2">
    </div>
    <div class="d-lg-flex justify-content-start align-items-center gap-3">
      <%= link_to "Back", admin_referrers_path,class:"btn btn-dark fw-medium" %>
      <h1 class="edit-heading">Editing Referrer</h1>
    </div>
    <div class="d-flex justify-content-between align-items-center">
      <%= render "form", referrer: @referrer %>
    </div>

  </div>

app/views/admin/referrers/index.html.erb
  <div class="main-content">
    <% if notice %>
      <div class="alert alert-danger" role="alert"><%= notice %></div>
    <% end %>
    <div class="d-flex justify-content-between align-items-center">
      <h1 class="mb-4">Listing Referrers</h1>
    </div>
    <div>
             <div>
    <%= form_with(url: admin_referrers_path, method: :get) do |f| %>
      <div class="form-group">
        <%= f.text_field :paytm_number, placeholder: "Search by paytm_number", class: "form-control" %>
      </div>
    <% end %>
  </div>
      <%= render "referrer" %>
      <%= paginate @referrers %>
    </div>
  </div>

app/views/admin/referrers/new.html.erb
<h1>New referrer</h1>

<%= render "form", referrer: @referrer %>

<br>

<div>
  <%= link_to "Back to referrers", admin_referrers_path %>
</div>

app/views/admin/referrers/show.html.erb
  <div class="main-content container">
    <% if notice %>
    <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>
    <div class="ms-2 mt-2">
    </div>

    <div class="d-lg-flex justify-content-start align-items-center gap-3">
      <%= link_to "Back", admin_referrers_path,class:"btn btn-dark fw-medium" %>
      <h1>Referrer: #<%= @referrer.id %></h1>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Live Offer Id</label>
          <h2 class="form-control"><%= @referrer.live_offer_id %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">App Offer Id</label>
          <h2 class="form-control"><%= @referrer.app_offer_id %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Click Id</label>
          <h2 class="form-control"><%= @referrer.click_id %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Affiliate Id</label>
          <h2 class="form-control"><%= @referrer.affiliate_id %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Paytm Number</label>
          <h2 class="form-control"><%= @referrer.paytm_number %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Upi Id</label>
          <h2 class="form-control"><%= @referrer.upi_id %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Source Ip</label>
          <h2 class="form-control"><%= @referrer.source_ip %></h2>
        </div>
      </div>

      <div class="col-md-6">

        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Aff Status</label>
          <h2 class="form-control"><%= @referrer.aff_status %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Ref Status</label>
          <h2 class="form-control"><%= @referrer.ref_status %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Aff Order Id</label>
          <h2 class="form-control"><%= @referrer.aff_order_id %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Ref Order Id</label>
          <h2 class="form-control"><%= @referrer.ref_order_id %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Aff Pay Response</label>
          <h2 class="form-control"><%= @referrer.aff_pay_response %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Ref Pay Response</label>
          <h2 class="form-control"><%= @referrer.ref_pay_response %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Created At</label>
          <h2 class="form-control"><%= @referrer.created_at.strftime('%d/%m/%y %H:%M:%S %p')%></h2>
        </div>
      </div>
    </div>

    <div class="form-group p-2 mt-4">
      <div class="col-sm-offset-2 col-sm-10">
        <%= link_to "Edit", edit_admin_referrers_path , class: "btn edit-save-btn text-light fw-medium w-25" %>
      </div>
    </div>
  </div>