config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  root "main#index"
  
  get "/offers/:app_offer_id" => "main#offer"
  post "/offers/:app_offer_id" => "referrers#create"
  get "/refer" => "main#refer"
  get "/refer/:app_offer_id" => "main#refer"
  get "/referral" => "main#referral"
  get "/profile" => "main#profile"
  get "/postback" => "main#postback"
  post "/profile" => "app_redeems#create"
  get "/logout" => "main#logout"
  get 'google_login' => "logins#google_login"
  get "/gameaward/:award_id" => "gameaward#index"
  post "/gameaward/:award_id" => "gameaward#create"
  get '/admin' => 'admin/manager#new'
  post '/admin' => 'admin/manager#create'
  get '/admin/logout' => 'admin/manager#destroy'
 
 namespace :admin do 

  resources :campaign_infos
  resources :app_offers
  resources :referrers
  resources :affiliates     
  resources :articles
  resources :app_banners
  resources :game_awards
  resources :list_redeems
   
 end

  get "/admin/app_offers/:app_offer_id/edit/event/new" => "admin/event#new"
  post "/admin/app_offers/:app_offer_id/edit/event/new" => "admin/event#create"
  get "/admin/app_offers/:app_offer_id/edit/event/:event_id/edit" => "admin/event#edit"
  post "/admin/app_offers/:app_offer_id/edit/event/:event_id/edit" => "admin/event#update"
  get "/admin/app_offers/:app_offer_id/edit/event/:event_id/" => "admin/event#destroy"

  get "/admin/game_rewards/" => "admin/game_rewards#index"
  get "/admin/app_redeems/" => "admin/list_redeems#index"
  get "/admin/app_redeems/:id/" => "admin/list_redeems#show"
  get "/admin/app_redeems/:id/edit" => "admin/list_redeems#edit"
  post "/admin/app_redeems/:id/edit" => "admin/list_redeems#update"
  get "/admin/ref_user/:id" => "admin/ref_user#show"
  get "/admin/postbacks" => "admin/event_postbacks#index"

  post "/payout" => "list_redeems#payout"

end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
	paginates_per 10
	
end

app/models/app_banner.rb
class AppBanner < ApplicationRecord
	paginates_per 10
	
end

app/models/app_offer.rb
class AppOffer < ApplicationRecord
  paginates_per 10
  
  has_many :events
end

app/models/app_redeem.rb
class AppRedeem < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	paginates_per 10
	
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  paginates_per 10
  
  belongs_to :campaign_info , foreign_key: "campaign_info_id", class_name: "CampaignInfo"
end

app/models/campaign_info.rb
class CampaignInfo < ApplicationRecord
  paginates_per 10
  
  has_many :campaign
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :app_offer,foreign_key: "app_offer_id",class_name: "AppOffer"
end

app/models/event_postback.rb
class EventPostback < ApplicationRecord
	paginates_per 10
	
end

app/models/game_award.rb
class GameAward < ApplicationRecord
	paginates_per 10
	
end

app/models/game_reward.rb
class GameReward < ApplicationRecord
	paginates_per 10
	
end

app/models/list_redeem.rb
class ListRedeem < ApplicationRecord
	paginates_per 10
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_secure_password

  validates :username, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/postback.rb
class Postback < ApplicationRecord
	belongs_to :referrer
end

app/models/ref_user.rb
class RefUser < ApplicationRecord
end

app/models/referrer.rb
class Referrer < ApplicationRecord
	paginates_per 10
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < ApplicationController
  layout  "admin"
  before_action :set_article, only: %i[ show edit update destroy ]
  def index
     if params[:title].present?
      @articles = Article.where("title LIKE ?", "%#{params[:title]}%").order("id DESC").page(params[:page])
    else
    @articles = Article.all.order("id DESC").page(params[:page])
    end
  end
  def show
  end
  def new
    @article = Article.new
  end
  def edit
  end
  def create
    @article = Article.new(article_params)
      if @article.save
         redirect_to admin_article_url(@article), notice: "Article was successfully created."
      else
       render :new, status: :unprocessable_entity
    end
  end
  def update
      if @article.update(article_params)
         redirect_to admin_article_url(@article), notice: "Article was successfully updated."
      else
        render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @article.destroy!
      redirect_to admin_articles_url, notice: "Article was successfully destroyed."
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :description, :img_url, :published_date, :highlight, :category, :permalink)
    end
end

end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/helpers/app_banners_helper.rb
module AppBannersHelper
end

app/helpers/app_offers_helper.rb
module AppOffersHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/referrers_helper.rb
module ReferrersHelper
end

app/views/admin/articles/_article.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th scope="col" class="fs-5">Id</th>
    <th scope="col" class="fs-5">Image</th>
    <th scope="col" class="fs-5">Title</th>
    <th scope="col" class="fs-5">Published Date</th>
    <th scope="col" class="fs-5">Status</th>
    <th scope="col" class="fs-5">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <th class="fs-5">
        <a href="/admin/articles/<%= article.id %>"><%= article.id %></a>
      </th>
      <td>
        <% if article.img_url %>
          <%= image_tag article.img_url,style:"width:200px" %>
        <% end %>
      </td>
      <td class="fs-5"><%= article.title %></td>
      <td class="fs-5"><%= article.created_at.strftime("%d/%m/%y  %I:%M:%S %p") %></td>
      <td class="fs-5">
        <% if article.highlight %>
          <i class="fa-solid fa-check text-success fs-3" ></i>
        <% else %>
          <i class="fa-solid fa-xmark text-danger fs-3" ></i>
        <% end %>
      </td>
      <td><%= link_to "Edit", edit_admin_article_path(article),class:"btn bg-dark text-light"%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/articles/_form.html.erb
<%= stylesheet_link_tag "admin" %>
<%= form_with(model: article,url:admin_article_path, class: "form-horizontal") do |form| %>
  <% if article.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this app_offer from being saved:</h2>
      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group p-2">
        <%= form.label :title, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :img_url, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :img_url, class: "form-control" %>
      </div>
        <div class="form-group p-2 d-flex align-items-center gap-2">
          <%= form.label :highlight, class: "control-label fs-5 fw-medium" %>
          <%= form.check_box :highlight, class: "form-check-input" %>
        </div>
      </div>
    <div class="col-md-6">
      <div class="form-group p-2">
        <%= form.label :description, class: "control-label fs-5 fw-medium" %>
        <%= form.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group p-2">
        <%= form.label :permalink, class: "control-label fs-5 fw-medium" %>
        <%= form.text_field :permalink, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group p-2">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit "Save", class: "btn edit-save-btn text-light fw-medium" %>
    </div>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
  <div class="main-content container">
    <% if notice %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>
    <div class="ms-2 mt-2">
    </div>

    <div class="d-lg-flex justify-content-start align-items-center gap-3">
      <%= link_to "Back", admin_articles_path,class:"btn btn-dark fw-medium" %>
      <h1 class="edit-heading">Editing Article</h1>
    </div>
    <div class="d-flex justify-content-between align-items-center">
      <%= render "form", article: @article %>
    </div>
  </div>

app/views/admin/articles/index.html.erb
  <div class="main-content">
    <% if notice %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>
    <div class="d-flex justify-content-between align-items-center">
      <h1 class="mb-4">Listing Articles </h1>
      <%= link_to "New article", new_admin_article_path ,class:"btn btn-success mb-4"%>
    </div>
    <div>
        <%= form_with(url: admin_articles_path, method: :get) do |f| %>
      <div class="form-group">
        <%= f.text_field :title, placeholder: "Search by title", class: "form-control" %>
      </div>
    <% end %>
    </div>
        <%= render "article" %>
        <%= paginate @articles %>
    </div>
  </div>

app/views/admin/articles/new.html.erb
  <div class="main-content container">
    <p style="color: green"><%= notice %></p>
    <div class="d-flex justify-content-start gap-3">
      <div class="ms-2 mt-2">
        <%= link_to "Back", admin_articles_path,class:"btn btn-dark fw-medium" %>
      </div>
      <h1 class="mb-4">New Article</h1>
    </div>
    <div class="d-flex justify-content-between align-items-center">
      <%= render "form", article: @article %>
    </div>
  </div>

app/views/admin/articles/show.html.erb
  <div class="main-content container">
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <div class="d-lg-flex justify-content-start align-items-center gap-3">
      <%= link_to "Back", admin_articles_path,class:"btn btn-dark fw-medium" %>
      <h1><%= @article.title %></h1>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Title</label>
          <h2 class="form-control"><%= @article.title %></h2>
        </div>

        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">description</label>
          <h2 class="form-control"><%= @article.description %></h2>
        </div>


        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Image Url</label>
          <h2 class="form-control"><%= @article.img_url %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Category</label>
          <h2 class="form-control"><%= @article.category %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Permalink</label>
          <h2 class="form-control"><%= @article.permalink %></h2>
        </div>

        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Published Date</label>
          <h2 class="form-control"><%= @article.published_date %></h2>
        </div>
        <div class="d-lg-flex gap-3 mt-4">
          <div class="form-group p-2 d-flex align-items-center gap-2">
            <label class="form-check-label" for="exampleCheck1">Highlight</label>
            <input disabled type="checkbox" class="form-check-input" id="exampleCheck1" <%= @article.highlight ? 'checked' : '' %> >
          </div>
        </div>
      </div>

      <div class="col-md-6">
      </div>
    </div>
    <div class="form-group p-2 mt-4">
      <div class="col-sm-offset-2 col-sm-10">
        <%= link_to "Edit", edit_admin_article_path(@article) , class: "btn btn-dark text-light fw-medium me-3" %>
      </div>
    </div>
</div>