config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check

  root "main#index"
  
  get "/offers/:app_offer_id" => "main#offer"
  post "/offers/:app_offer_id" => "referrers#create"
  get "/refer" => "main#refer"
  get "/refer/:app_offer_id" => "main#refer"
  get "/referral" => "main#referral"
  get "/profile" => "main#profile"
  get "/postback" => "main#postback"
  post "/profile" => "app_redeems#create"
  get "/logout" => "main#logout"
  get 'google_login' => "logins#google_login"
  get "/gameaward/:award_id" => "gameaward#index"
  post "/gameaward/:award_id" => "gameaward#create"
  get '/admin' => 'admin/manager#new'
  post '/admin' => 'admin/manager#create'
  get '/admin/logout' => 'admin/manager#destroy'
 
 namespace :admin do 

  resources :campaign_infos
  resources :app_offers
  resources :referrers
  resources :affiliates     
  resources :articles
  resources :app_banners
  resources :game_awards
  resources :list_redeems
   
 end

  get "/admin/app_offers/:app_offer_id/edit/event/new" => "admin/event#new"
  post "/admin/app_offers/:app_offer_id/edit/event/new" => "admin/event#create"
  get "/admin/app_offers/:app_offer_id/edit/event/:event_id/edit" => "admin/event#edit"
  post "/admin/app_offers/:app_offer_id/edit/event/:event_id/edit" => "admin/event#update"
  get "/admin/app_offers/:app_offer_id/edit/event/:event_id/" => "admin/event#destroy"

  get "/admin/game_rewards/" => "admin/game_rewards#index"
  get "/admin/app_redeems/" => "admin/list_redeems#index"
  get "/admin/app_redeems/:id/" => "admin/list_redeems#show"
  get "/admin/app_redeems/:id/edit" => "admin/list_redeems#edit"
  post "/admin/app_redeems/:id/edit" => "admin/list_redeems#update"
  get "/admin/ref_user/:id" => "admin/ref_user#show"
  get "/admin/postbacks" => "admin/event_postbacks#index"

  post "/payout" => "list_redeems#payout"

end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
	paginates_per 10
	
end

app/models/app_banner.rb
class AppBanner < ApplicationRecord
	paginates_per 10
	
end

app/models/app_offer.rb
class AppOffer < ApplicationRecord
  paginates_per 10
  
  has_many :events
end

app/models/app_redeem.rb
class AppRedeem < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	paginates_per 10
	
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  paginates_per 10
  
  belongs_to :campaign_info , foreign_key: "campaign_info_id", class_name: "CampaignInfo"
end

app/models/campaign_info.rb
class CampaignInfo < ApplicationRecord
  paginates_per 10
  
  has_many :campaign
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :app_offer,foreign_key: "app_offer_id",class_name: "AppOffer"
end

app/models/event_postback.rb
class EventPostback < ApplicationRecord
	paginates_per 10
	
end

app/models/game_award.rb
class GameAward < ApplicationRecord
	paginates_per 10
	
end

app/models/game_reward.rb
class GameReward < ApplicationRecord
	paginates_per 10
	
end

app/models/list_redeem.rb
class ListRedeem < ApplicationRecord
	paginates_per 10
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_secure_password

  validates :username, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/postback.rb
class Postback < ApplicationRecord
	belongs_to :referrer
end

app/models/ref_user.rb
class RefUser < ApplicationRecord
end

app/models/referrer.rb
class Referrer < ApplicationRecord
	paginates_per 10
end

app/controllers/admin/app_offers_controller.rb
module Admin
  class AppOffersController < AdminController
  layout  "admin"
  before_action :set_app_offer, only: %i[show edit update]
  def index
    if params[:offer_name].present?
      @app_offers = AppOffer.where("offer_name LIKE ?", "%#{params[:offer_name]}%").order("id DESC").page(params[:page])
    else
      @app_offers = AppOffer.all.order("id DESC").page(params[:page])
    end
  end
  def new
    @app_offer = AppOffer.new
  end
  def show
    @events = Event.where(app_offer_id:params[:id])
  end
  def edit
    @events = @app_offer.events.all
  end
  def create
    @app_offer = AppOffer.new(app_offer_params)
      if @app_offer.save
    redirect_to admin_app_offers_path, notice: "App offer was successfully created."
      else
     render :new, status: :unprocessable_entity
    end
  end
  def update
      if @app_offer.update(app_offer_params)
        redirect_to admin_app_offers_path , notice: "App offer updated successfully."
      else
        render :edit, status: :unprocessable_entity
      end
    end

  private
    def set_app_offer
      @app_offer = AppOffer.find(params[:id])
    end
    def app_offer_params
      params.require(:app_offer).permit(:offer_name, :identifier, :description, :instructions, :payout_amount, :retention_offer, :retention_amount, :retention_day, :action_url, :refer_amount, :image_url, :daily_cap, :status, :whatsapp_link, :event_offer, :priority, :insta_offer)
    end
end

end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/helpers/app_banners_helper.rb
module AppBannersHelper
end

app/helpers/app_offers_helper.rb
module AppOffersHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/referrers_helper.rb
module ReferrersHelper
end

app/views/admin/app_offers/_app_offer.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th scope="col" class="fs-5">Id</th>
    <th scope="col" class="fs-5">Image</th>
    <th scope="col" class="fs-5">Offer Name</th>
    <th scope="col" class="fs-5">Identifier</th>
    <th scope="col" class="fs-5">PayAmt/RefAmt</th>
    <th scope="col" class="fs-5">Status</th>
    <th scope="col" class="fs-5">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @app_offers.each do |app_offer| %>
    <tr>
      <th class="fs-5">
        <a href="/admin/app_offers/<%= app_offer.id %>"><%= app_offer.id %></a>
      </th>
      <td><%= image_tag app_offer.image_url,style: "width:80px" %></td>
      <td class="fs-5"><%= app_offer.offer_name %></td>
      <td class="fs-5"><%= app_offer.identifier %></td>
      <td class="fs-5"><%= app_offer.payout_amount %> / <%= app_offer.refer_amount%></td>
      <td class="fs-5">
        <% if app_offer.status %>
          <i class="fa-solid fa-check text-success fs-3" ></i>
        <% else %>
          <i class="fa-solid fa-xmark text-danger fs-3" ></i>
        <% end %>
      </td>
      <td>
        <%= link_to "Edit", edit_admin_app_offer_path(app_offer),class:"btn bg-dark text-light"%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/app_offers/_form.html.erb
  <%= form_with(model: app_offer,url:admin_app_offers_path ,class: "form-horizontal") do |form| %>
    <% if app_offer.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(app_offer.errors.count, "error") %> prohibited this app_offer from being saved:</h2>
        <ul>
          <% app_offer.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group p-2 w-100">
          <%= form.label :offer_name, class: "control-label fs-5 fw-medium" %>
          <%= form.text_field :offer_name, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :identifier, class: "control-label fs-5 fw-medium" %>
          <%= form.text_field :identifier, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :instructions, class: "control-label fs-5 fw-medium" %>
          <%= form.text_area :instructions, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :action_url, class: "control-label fs-5 fw-medium" %>
          <%= form.text_field :action_url, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :payout_amount, class: "control-label fs-5 fw-medium" %>
          <%= form.text_field :payout_amount, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :retention_amount, class: "control-label fs-5 fw-medium" %>
          <%= form.text_field :retention_amount, class: "form-control" %>
        </div>
        <div class="d-lg-flex gap-3 mt-2 ">
          <div class="form-group p-2 d-flex align-items-center gap-2">
            <%= form.label :status, class: "control-label fs-5 fw-medium" %>
            <%= form.check_box :status, class: "form-check-input" %>
          </div>
          <div class="form-group p-2 d-flex align-items-center gap-2">
            <%= form.label :retention_offer, class: "control-label fs-5 fw-medium" %>
            <%= form.check_box :retention_offer, class: "form-check-input" %>
          </div>

          <div class="form-group p-2 d-flex align-items-center gap-2">
            <%= form.label :event_offer, class: "control-label fs-5 fw-medium" %>
            <%= form.check_box :event_offer, class: "form-check-input" %>
          </div>

          <div class="form-group p-2 d-flex align-items-center gap-2">
            <%= form.label :insta_offer, class: "control-label fs-5 fw-medium" %>
            <%= form.check_box :insta_offer, class: "form-check-input" %>
          </div>
        </div>

      </div>

      <div class="col-md-6">
        <div class="form-group p-2 w-100">
          <%= form.label :retention_day, class: "control-label fs-5 fw-medium" %>
          <%= form.text_field :retention_day, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :whatsapp_link, class: "control-label fs-5 fw-medium" %>
          <%= form.text_field :whatsapp_link, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :description, class: "control-label fs-5 fw-medium" %>
          <%= form.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :refer_amount, class: "control-label fs-5 fw-medium" %>
          <%= form.text_field :refer_amount, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :image_url, class: "control-label fs-5 fw-medium" %>
          <%= form.text_field :image_url, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :daily_cap, class: "control-label fs-5 fw-medium" %>
          <%= form.number_field :daily_cap, class: "form-control" %>
        </div>
        <div class="form-group p-2">
          <%= form.label :priority, class: "control-label fs-5 fw-medium" %>
          <%= form.number_field :priority, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group p-2">
      <div class="col-sm-offset-2 col-sm-10">
        <%= form.submit "Save", class: "btn edit-save-btn text-light fw-medium" %>
      </div>
    </div>

  <% end %>

app/views/admin/app_offers/edit.html.erb
  <div class="main-content container">
    <% if notice %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>
    <div class="ms-2 mt-2">
    </div>
      <div class="d-lg-flex justify-content-between align-items-center gap-3 me-5">
       <div class="d-flex gap-3 align-items-center justify-content-start">
         <%= link_to "Back", admin_app_offers_path,class:"btn btn-dark fw-medium" %>
        <h1 class="edit-heading">Editing app offer</h1>
       </div>
        <a href="/admin/app_offers/<%= @app_offer.id %>/edit/event/new" class="btn btn-success fw-medium me-5 w-25">New Event</a>
    </div>
    <div class="d-flex justify-content-between align-items-center">
      <%= render "form", app_offer: @app_offer %>
    </div>
  </div>

app/views/admin/app_offers/index.html.erb
<div class="main-content">
  <% if notice %>
    <div class="alert alert-success" role="alert"><%= notice %></div>
  <% end %>

  <div class="d-flex justify-content-between align-items-center">
    <h1 class="mb-4">Listing App offers</h1>
    <%= link_to "New app offer", new_admin_app_offer_path, class: "btn btn-success mb-4" %>
  </div>

  <div id="app_offers">
    <%= form_with(url: admin_app_offers_path, method: :get) do |f| %>
      <div class="form-group">
        <%= f.text_field :offer_name, placeholder: "Search by offer name", class: "form-control" %>
      </div>
    <% end %>

    <%= render "app_offer" %>
<%= paginate @app_offers %>

  </div>
</div>

app/views/admin/app_offers/new.html.erb
 <div class="main-content container">
    <p style="color: green"><%= notice %></p>
<div class="d-flex justify-content-start gap-3">
  <div class="ms-2 mt-2">
    <%= link_to "Back", admin_app_offers_path,class:"btn btn-dark fw-medium" %>
  </div>
  <h1 class="mb-4">New App Offer</h1>

</div>
    <div class="d-flex justify-content-between align-items-center">
      <%= render "form", app_offer: @app_offer %>
    </div>
  </div>

app/views/admin/app_offers/show.html.erb
 <div class="main-content container">
   <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <div class="d-lg-flex justify-content-start align-items-center gap-3">
      <%= link_to "Back", admin_app_offers_path,class:"btn btn-dark fw-medium" %>
      <h1><%= @app_offer.offer_name %></h1>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Offer Name</label>
          <h2 class="form-control"><%= @app_offer.offer_name %></h2>
        </div>

        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Identifier</label>
          <h2 class="form-control"><%= @app_offer.identifier %></h2>
        </div>


        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Instructions</label>
          <h2 class="form-control"><%= @app_offer.instructions %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Action Url</label>
          <h2 class="form-control"><%= @app_offer.action_url %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Payout Amount</label>
          <h2 class="form-control"><%= @app_offer.payout_amount %></h2>
        </div>


        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Retention Amount</label>
          <h2 class="form-control"><%= @app_offer.retention_amount %></h2>
        </div>
        <div class="d-lg-flex gap-3 mt-4">
          <div class="form-group p-2 d-flex align-items-center gap-2">
            <label class="form-check-label" for="exampleCheck1">Status</label>
            <input disabled type="checkbox" class="form-check-input" id="exampleCheck1" <%= @app_offer.status ? 'checked' : '' %> >
          </div>
          <div class="form-group p-2 d-flex align-items-center gap-2">
            <label class="form-check-label" for="exampleCheck1">Retention Offer</label>
            <input disabled type="checkbox" class="form-check-input" id="exampleCheck1" <%= @app_offer.retention_offer ? 'checked' : '' %> >
          </div>

          <div class="form-group p-2 d-flex align-items-center gap-2">
            <label class="form-check-label" for="exampleCheck1">Event Offer</label>
            <input disabled type="checkbox" class="form-check-input" id="exampleCheck1" <%= @app_offer.event_offer ? 'checked' : "" %> >
          </div>

          <div class="form-group p-2 d-flex align-items-center gap-2">
            <label class="form-check-label" for="exampleCheck1">Insta Offer</label>
            <input disabled type="checkbox" class="form-check-input" id="exampleCheck1" <%= @app_offer.insta_offer ? 'checked' : "" %> >
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Retention Day</label>
          <h2 class="form-control"><%= @app_offer.retention_day %></h2>
        </div>

        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">WhatsApp Link</label>
          <h2 class="form-control"><%= @app_offer.whatsapp_link %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Description</label>
          <h2 class="form-control"><%= @app_offer.description %></h2>
        </div>

        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Refer Amount</label>
          <h2 class="form-control"><%= @app_offer.refer_amount %></h2>
        </div>

        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Image Url</label>
          <h2 class="form-control"><%= @app_offer.image_url %></h2>
        </div>

        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Daily Cap</label>
          <h2 class="form-control"><%= @app_offer.daily_cap %></h2>
        </div>
        <div class="form-group p-2">
          <label class="control-label fs-5 fw-medium">Priority</label>
          <h2 class="form-control"><%= @app_offer.priority %></h2>
        </div>
      </div>
    </div>
      <% @events.each do |event| %>
    <div class="w-100 d-flex flex-column gap-3">
       <div class="d-flex align-items-center">
          <div class="form-group p-2 w-100">
          <label class="control-label fs-5 fw-medium">Event Order</label>
          <h2 class="form-control"><%= event.event_order %></h2>
        </div>
        <div class="form-group p-2 w-100">
          <label class="control-label fs-5 fw-medium">Event Title</label>
          <h2 class="form-control"><%= event.event_title %></h2>
        </div>
         <div class="form-group p-2 w-100">
          <label class="control-label fs-5 fw-medium">Event Amount</label>
          <h2 class="form-control"><%= event.event_amount %></h2>
        </div>
        <div class="form-group p-2 w-100">
          <label class="control-label fs-5 fw-medium">Pay Type</label>
          <h2 class="form-control"><%= event.pay_type %></h2>
        </div>
        <div class="form-group p-2  mt-4">
          <a class="btn btn-dark" href="/admin/app_offers/<%= @app_offer.id %>/edit/event/<%= event.id %>/edit">Edit</a>
        </div>
        <div class="form-group p-2 w-100 mt-4">
          <a class="btn btn-danger" href="/admin/app_offers/<%= @app_offer.id %>/edit/event/<%= event.id %>">Delete</a>
        </div>
       </div>
    </div>
      <% end %>
    <div class="form-group p-2 mt-4">
      <div class="col-sm-offset-2 col-sm-10">
        <%= link_to "Edit", edit_admin_app_offer_path , class: "btn btn-dark text-light fw-medium me-3" %>
      </div>
    </div>
  </div>